[tool.black]
line-length = 79
# target-version = ['py37']
include = '\.pyi?$'
exclude = '''

(
  /(
      config
    | \.git
    | \.idea
    | \.pytest_cache
    | \.mypy_cache
    | \.vscode
    | docs
  )/
)
'''

[tool.isort]
line_length=79
known_first_party="pybbbc"
multi_line_output=3
include_trailing_comma=true
force_grid_wrap=0
use_parentheses=true
